spring:
  data:
    redis:
      host: 192.168.154.130
      port: 6379
      password:
  jmx:
    enabled: false

  datasource:
    url: jdbc:postgresql://192.168.154.130:5432/lab17
    username: dev
    password: Mvmvmv99@
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true