spring:
  data:
    redis:
      host: 103.56.162.107
      port: 6379
      password: 1231234
  jmx:
    enabled: false

  datasource:
    url: jdbc:postgresql://103.56.162.107:5432/lab17
    username: anhdq
    password: 1231234
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://192.168.154.130:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 192.168.154.1