server:
  port: 8888

spring:
  profiles:
    active: native
  output:
    ansi:
      enabled: always
  cloud:
    config:
      server:
        #        git:
        #          uri: https://github.com/dj-xuyenchi/config-server.git
        native:
          search-locations: classpath:/config
        encrypt:
          enabled: false
        bootstrap: true
      allow-override: true

management:
  endpoints:
    web:
      exposure:
        include: health
